# Generated by Django 2.1.1 on 2020-03-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=None)),
                ('email', models.CharField(default=None, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=32)),
                ('state', models.BooleanField(default=None)),
                ('pub_date', models.DateField(default=None)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('authors', models.ManyToManyField(default=None, to='api.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=32)),
                ('email', models.CharField(default=None, max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Publish'),
        ),
    ]
