# Generated by Django 2.1.1 on 2020-03-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200316_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetail',
            name='tel',
            field=models.CharField(max_length=32),
        ),
    ]
