# Generated by Django 2.1.1 on 2020-03-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200317_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=20)),
                ('dep', models.CharField(max_length=32)),
                ('pro', models.CharField(max_length=32)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='comment_count',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='book',
            name='poll_count',
            field=models.IntegerField(default=100),
        ),
    ]
